[mgr]
prepend_keymap = [
	{ on = "<Space>", run = "noop", desc = "Disable default Space selection" },
	# native yazi keymaps 
	{ on = "<Esc>", run = [ "escape --all", "unyank" ], desc = "Clear find, visual, filter, selection, search and yank state" },
	{ on = "v", run = "toggle", desc = "Toggle hovered file selection" },
	{ on = "V", run = "visual_mode", desc = "Enter visual mode to select a continuous range of files" },

	# wsl-clipboard plugin keymaps
	{ on = "y", run = [ "escape --visual", "plugin wsl-clipboard -- toggle --copy" ], desc = "Toggle yank to Windows clipboard" },
	{ on = "Y", run = "noop", desc = "Disable default yank cancel" },
	{ on = "x", run = [ "escape --visual", "plugin wsl-clipboard -- toggle --cut" ], desc = "Toggle cut to Windows clipboard" },
	{ on = "X", run = "noop", desc = "Disable default yank cancel" },
	{ on = "p", run = "plugin wsl-clipboard -- paste", desc = "Paste from Windows clipboard" },
	{ on = "P", run = "noop", desc = "Disable default overwrite paste" },
]

[input]
prepend_keymap = [
	{ on = "d", run = "delete", desc = "Delete selected characters" },
	{ on = "D", run = [ "delete", "move eol" ], desc = "Delete until EOL"},
	{ on = "x", run = [ "delete", "move 1 --in-operating" ], desc = "Delete current character" },
	{ on = "c", run = "delete --insert", desc = "Delete selected characters and enter insert mode" },
	{ on = "C", run = [ "delete --insert", "move eol" ], desc = "Delete until EOL and enter insert mode" },
	{ on = "s", run = "noop", desc = "Disable default substitute" },
	{ on = "S", run = "noop", desc = "Disable default substitute line" }
]
